from datetime import datetime, timezone
from typing import List, Optional, Dict, Any
from ..models.event import Event


def parse_timestamp(ts_str: str) -> datetime:
    """Parse ISO 8601 string to timezone-aware UTC datetime."""
    try:
        cleaned = ts_str.replace("Z", "+00:00")
        dt = datetime.fromisoformat(cleaned)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt
    except Exception:
        return datetime.now(timezone.utc)


class DetectionCandidate:
    """Candidate detection generated by a rule before database persistence."""

    def __init__(
        self,
        event_id: int,
        timestamp: str,
        rule_id: str,
        detection_name: str,
        severity: str,
        source_ip: str,
        destination_ip: str,
        username: Optional[str],
        description: str,
        evidence: Dict[str, Any],
        status: str = "new",
    ):
        self.event_id = event_id
        self.timestamp = timestamp
        self.rule_id = rule_id
        self.detection_name = detection_name
        self.severity = severity
        self.source_ip = source_ip
        self.destination_ip = destination_ip
        self.username = username
        self.description = description
        self.evidence = evidence
        self.status = status


def evaluate_rules(
    current_event: Event,
    all_events: List[Event],
    failed_login_threshold: int = 5,
    failed_login_window_seconds: int = 300,
    success_after_failure_threshold: int = 2,
    success_after_failure_window_seconds: int = 900,
) -> List[DetectionCandidate]:
    """
    Evaluate all 8 hybrid detection rules against current_event in chronological context.
    Returns list of candidate detections.
    """
    candidates: List[DetectionCandidate] = []
    current_dt = parse_timestamp(current_event.timestamp)
    metadata = current_event.metadata_json or {}

    # -------------------------------------------------------------
    # Rule 1 — Repeated Failed Logins (AUTH-001)
    # Threshold: >= 5 failed logins from same source to same destination within 5 minutes.
    # -------------------------------------------------------------
    if current_event.event_type == "login_failed":
        # Look back for login_failed events matching source and destination within window
        matching_failures = [
            e for e in all_events
            if e.event_type == "login_failed"
            and e.source_ip == current_event.source_ip
            and e.destination_ip == current_event.destination_ip
            and 0 <= (current_dt - parse_timestamp(e.timestamp)).total_seconds() <= failed_login_window_seconds
            and parse_timestamp(e.timestamp) <= current_dt
        ]

        if len(matching_failures) >= failed_login_threshold:
            candidates.append(
                DetectionCandidate(
                    event_id=current_event.id,
                    timestamp=current_event.timestamp,
                    rule_id="AUTH-001",
                    detection_name="Repeated Failed Login Attempts",
                    severity="high",
                    source_ip=current_event.source_ip,
                    destination_ip=current_event.destination_ip,
                    username=current_event.username,
                    description="Multiple failed authentication attempts detected within time window.",
                    evidence={
                        "failed_attempts": len(matching_failures),
                        "window_minutes": failed_login_window_seconds // 60,
                        "threshold": failed_login_threshold,
                    },
                )
            )

    # -------------------------------------------------------------
    # Rule 2 — Successful Login After Failed Attempts (AUTH-002)
    # Trigger: login_success occurs after repeated failed logins from same source to destination.
    # -------------------------------------------------------------
    elif current_event.event_type == "login_success":
        prior_failures = [
            e for e in all_events
            if e.event_type == "login_failed"
            and e.source_ip == current_event.source_ip
            and e.destination_ip == current_event.destination_ip
            and 0 < (current_dt - parse_timestamp(e.timestamp)).total_seconds() <= success_after_failure_window_seconds
        ]

        if len(prior_failures) >= success_after_failure_threshold:
            candidates.append(
                DetectionCandidate(
                    event_id=current_event.id,
                    timestamp=current_event.timestamp,
                    rule_id="AUTH-002",
                    detection_name="Successful Login After Failed Attempts",
                    severity="high",
                    source_ip=current_event.source_ip,
                    destination_ip=current_event.destination_ip,
                    username=current_event.username,
                    description="Successful authentication observed after repeated failed login attempts from source IP.",
                    evidence={
                        "prior_failed_attempts": len(prior_failures),
                        "window_minutes": success_after_failure_window_seconds // 60,
                    },
                )
            )

    # -------------------------------------------------------------
    # Rule 3 — Privilege Escalation (PRIV-001)
    # -------------------------------------------------------------
    elif current_event.event_type == "privilege_escalation":
        candidates.append(
            DetectionCandidate(
                event_id=current_event.id,
                timestamp=current_event.timestamp,
                rule_id="PRIV-001",
                detection_name="Privilege Escalation Detected",
                severity="high",
                source_ip=current_event.source_ip,
                destination_ip=current_event.destination_ip,
                username=current_event.username,
                description="Privilege escalation activity detected on host.",
                evidence={
                    "service": current_event.service,
                    "protocol": current_event.protocol,
                    "metadata": metadata,
                },
            )
        )

    # -------------------------------------------------------------
    # Rule 4 — Database Access (DATA-001)
    # Security-relevant event recorded for correlation, not automatically malicious.
    # -------------------------------------------------------------
    elif current_event.event_type == "database_access":
        candidates.append(
            DetectionCandidate(
                event_id=current_event.id,
                timestamp=current_event.timestamp,
                rule_id="DATA-001",
                detection_name="Database Access Detected",
                severity="medium",
                source_ip=current_event.source_ip,
                destination_ip=current_event.destination_ip,
                username=current_event.username,
                description="Database access event recorded for correlation and monitoring.",
                evidence={
                    "service": current_event.service,
                    "protocol": current_event.protocol,
                    "metadata": metadata,
                },
            )
        )

    # -------------------------------------------------------------
    # Rule 5 — Large Data Transfer (NET-001)
    # Security-relevant event, not automatically called exfiltration.
    # -------------------------------------------------------------
    elif current_event.event_type == "large_data_transfer":
        candidates.append(
            DetectionCandidate(
                event_id=current_event.id,
                timestamp=current_event.timestamp,
                rule_id="NET-001",
                detection_name="Large Data Transfer Detected",
                severity="medium",
                source_ip=current_event.source_ip,
                destination_ip=current_event.destination_ip,
                username=current_event.username,
                description="Large network data transfer detected across hosts.",
                evidence={
                    "service": current_event.service,
                    "protocol": current_event.protocol,
                    "metadata": metadata,
                },
            )
        )

    # -------------------------------------------------------------
    # Rule 6 — Port Scan (SCAN-001)
    # -------------------------------------------------------------
    elif current_event.event_type == "port_scan":
        candidates.append(
            DetectionCandidate(
                event_id=current_event.id,
                timestamp=current_event.timestamp,
                rule_id="SCAN-001",
                detection_name="Port Scan Detected",
                severity="medium",
                source_ip=current_event.source_ip,
                destination_ip=current_event.destination_ip,
                username=current_event.username,
                description="Port scanning activity detected from source IP.",
                evidence={
                    "service": current_event.service,
                    "protocol": current_event.protocol,
                    "metadata": metadata,
                },
            )
        )

    # -------------------------------------------------------------
    # Rule 7 — Suspicious HTTP Request (WEB-001)
    # -------------------------------------------------------------
    elif current_event.event_type == "suspicious_http_request":
        candidates.append(
            DetectionCandidate(
                event_id=current_event.id,
                timestamp=current_event.timestamp,
                rule_id="WEB-001",
                detection_name="Suspicious HTTP Request",
                severity="medium",
                source_ip=current_event.source_ip,
                destination_ip=current_event.destination_ip,
                username=current_event.username,
                description="Suspicious HTTP request detected targeting endpoint.",
                evidence={
                    "service": current_event.service,
                    "protocol": current_event.protocol,
                    "metadata": metadata,
                },
            )
        )

    # -------------------------------------------------------------
    # Rule 8 — Unusual Connection (CONN-001)
    # -------------------------------------------------------------
    elif current_event.event_type == "unusual_connection":
        candidates.append(
            DetectionCandidate(
                event_id=current_event.id,
                timestamp=current_event.timestamp,
                rule_id="CONN-001",
                detection_name="Unusual Network Connection",
                severity="low",
                source_ip=current_event.source_ip,
                destination_ip=current_event.destination_ip,
                username=current_event.username,
                description="Unusual network connection pattern observed.",
                evidence={
                    "service": current_event.service,
                    "protocol": current_event.protocol,
                    "metadata": metadata,
                },
            )
        )

    return candidates
